### ISSUE TITLE
ResponseType swallows coroutine CancellationExceptions

### ISSUE THREAD

**Issue by bogdanzurac** [tjek/tjek-android-sdk#39]
While using the `TjekAPI`, the `APIRequestBase.safeApiCall` method swallows potential coroutine `CancellationException`s.

This is a problem when we are trying to use the `TjekAPI` inside RxJava flows that wrap coroutines, because when the RxJava flows are cancelled, the associated coroutine's `CancellationException` is not properly propagated upstream, because it's caught by the `ResponseType.Error` from `APIRequestBase.safeApiCall` method. 

Due to this, we are unable to know when the coroutine is cancelled vs when an actual error occurs on the API layer. Hence, if we want to translate the `ResponseType.Error` back into an `Exception` for propagation through the RxJava error layer, the app essentially crashes, because the RxJava flow is already disposed by the time we want to propagate the underlying `CancellationException` upstream.

That's not to mention the fact that, because `ResponseType.Error` does not contain the `Exception` cause, it's also really terrible to figure out if it was caused by a `CancellationException` or not. We need to check if its `message` is equal to the string `RxSingleCoroutine was cancelled`.

A potential fix that I see here is to only catch business logic `Exceptions` and when encountering `CancellationException`s to  throw them upstream. Something along the lines of:

```
suspend fun <T : Any ,V> safeApiCall(decoder: suspend (V) -> T, apiCall: suspend () -> Response<V>): ResponseType<T> {
        try {
            val response = apiCall()
            checkHeaders(response.headers())
            if (response.isSuccessful) {
                val body = response.body()
                body?.let {
                    return ResponseType.Success(decoder(body))
                }
            }
            return error(response)
         } catch (e: Exception) {
            if (e is CancellationException) throw e
            return ResponseType.Error(message = e.message ?: e.toString())
        }
    }
```

**Comment by AgneseBussone** [comment]
I would like to avoid throwing exceptions, but instead wrap errors of any kind into an `Error` type.

Would it be a possible solution for your case if we added an optional `Exception` to `ResponseType.Error`? 
So you would be able to convert the Error into the Exception that cause it, if any.
Something like 

`class Error(val code: Int? = null, val message: String?, val exception: Exception? = null)`

and in case of a `CancellationException` the information would be propagated in the error:
```
try {
 ...
} catch (e: Exception) {
            return ResponseType.Error(exception = e)
        }
```

**Comment by bogdanzurac** [comment]
I would argue that coroutine `CancellationException`s are part of the coroutines underlying architecture and should not be handled by application logic (in this case translated into a custom `Result`-like class), just like we don't handle underlying JVM Errors. There have been endless discussions on this topic along the years, even related to the oficial `Result` class `runCatching` method: https://github.com/Kotlin/kotlinx.coroutines/issues/1814

So I would personally go for propagating the `CancellationException` upstream and let the caller handle it either automatically (through the `RxSingleCoroutine` flow in our case) or manually if it wants to.

But sure, if that's not what you would prefer for this API, then yes, exposing the underlying `Exception` as part of the `ResponseType.Error` class is definitely a good alternative as well.

**Comment by AgneseBussone** [comment]
The reason behind wrapping `Exceptions` in `Error` is because there are so many of them and I wanted to make things easy: you either get a result or you get an error. `Exceptions` usually represent an error of some kind.

I wasn't aware of that long discussion you linked, but  if `CancellationEx` is the way coroutines handle cancellation, then it shouldn't be included in `Error` because it's not an error.

I still want to avoid throwing exceptions, so I'll add a third type to `ResponseType` to represent a cancellation and return it in case of `CancellationEx`.
How does it sound?

**Comment by bogdanzurac** [comment]
If it were up to me, I would not treat the underlying implementation of Coroutines cancellation process as a business logic error `ResponseType`, since it's by definition not an error pertaining to the application logic. So I would throw it upstream, while still returning `ResponseType` for the regular application-level errors. This way, both concepts are handled in their own native way, without forcing an unnatural implementation for either of them.

Or, like you've mentioned previously, wrap the exceptions inside the `ResponseType.Error`. That way, any exception cause can still be handled by the caller if needed. I find this better than having a 3rd `ResponseType` specifically for coroutines cancellation.

**Comment by AgneseBussone** [comment]
From the official docs

> Cancellation is closely related to exceptions. Coroutines internally use CancellationException for cancellation, these exceptions are ignored by all handlers, so they should be used only as the source of additional debug information

I agree, we're not supposed to catch those.
So, I'll follow you suggestion and just re-throw them :) 
All the other exceptions will be wrapped in the `Error` type as additional info.

I'll try to release a new patch version asap.
