### ISSUE TITLE
Question to GetOfferFromIncito

### ISSUE THREAD

**Issue by VitaliyShuba** [tjek/tjek-android-sdk#47]
Hello. 

`IncitoEventListener` returns provides `IncitoOffer` when user clicks on offer. But this offer doesn't contain required info. So I tried to use `getOfferFromIncito` function.
This function returns offer with more data, but has no products. So for example if offer have multiple types of ice cream I am not able to get all those Ice creams. On iOS this is possible.

Can you please point me on correct direction, how to get these products?

**Comment by mortenbo** [comment]
@VitaliyShuba Hi! Thanks for your question. Can you please email us at services@tjek.com and ask your question there instead? Also which retailer you are trying to solve it for + your API key. Thanks!
